config/routes.rb
Rails.application.routes.draw do
  root 'manufacturers#index'
  devise_for :users
  resources :manufacturers
  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer_id, presence: true
  validates :color, presence: true
  validates :year, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1920,
    less_than_or_equal_to: Time.now.year
  }
  validates :mileage, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars
  validates :name,
  presence: true,
  uniqueness: { scope: :name }
  validates :country,
  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new

  end

  def create
    @car = Car.new(car_params)

    if @car.save
      flash[:notice] = "You've successfully submitted a vehicle!"
      redirect_to cars_path
    else
      flash[:alert] = "Fail"
      render "new"
    end
  end
  def show
    @car = Car.find(params[:id])
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      flash[:notice] = "You've successfully submitted a manufacturer!"
      redirect_to @manufacturer
    else
      flash[:alert] = "Fail"
      render "new"
    end
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end

end

app/views/cars/index.html.erb
<ul>
<% @cars.each do |car| %>

  <li><%= link_to car.manufacturer.name, car %>,
    <%= link_to car.color, car %>,
    <%= link_to car.year, car %>,
    <%= link_to car.mileage, car %>
  </li>
<% end %>
</ul>

app/views/cars/new.html.erb
<h1>New Vehicle</h1>
<%= simple_form_for @car do |f| %>


  <%= f.association :manufacturer %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.label :mileage %>
  <%= f.text_field :mileage %>


  <%= f.label :year %>
  <%= f.number_field(:year, in: 1924..2015) %>

  <%= f.submit 'Submit Vehicle' %>
  <% end %>

app/views/cars/show.html.erb
<h2>Vehicle</h2>
&nbsp;
<p>Manufacturer: <%= @car.manufacturer.name %></p>
&nbsp;
<p>Color: <%= @car.color %></p>
&nbsp;
<p>Year: <%= @car.year %></p>
&nbsp;
<p>Mileage: <%= @car.mileage %></p>
&nbsp;

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListing</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">CarListing</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
        <li><%= link_to "Create New Manufacturer", new_manufacturer_path %></li>
        <li><%= link_to "Add a Vehicle", new_car_path %></li>  
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/manufacturers/index.html.erb
<% @manufacturers.each do |manu| %>
  <h3><%= link_to manu.name, manu %></h3>
<% end %>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>
<%= form_for @manufacturer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :country %>
  <%= f.text_area :country %>

  <%= f.submit 'Submit Manufacturer' %>
  <% end %>

app/views/manufacturers/show.html.erb
<h2>Manufacturer</h2>
&nbsp;
<p>Name: <%= @manufacturer.name %></p>
&nbsp;
<p>Country: <%= @manufacturer.country %></p>
&nbsp;